sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
install:
- sudo add-apt-repository --yes ppa:avsm/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y opam
- opam init -y
- eval $(opam config env)
- opam config var root
- opam repo add coq-released https://coq.inria.fr/opam/released || echo
- travis_wait opam install -y coq.8.6.1 ocamlfind coq-unicoq
- opam list
script:
- ./configure.sh
- make clean && make
- cd tests && make clean && make -k

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/2fc197f36f7c587c0f59
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
