dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  matrix:
  - COQ_IMAGE="coqorg/coq:8.9"

install: |
  # Run the COQ container and display build metadata
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/Mtac2 -w /home/coq/Mtac2 ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    opam config list
    opam repo list
    opam list
    opam install -y coq-unicoq.v1.3+8.9
    "
script:
- echo -e "${ANSI_YELLOW}Building Mtac2...${ANSI_RESET}" && echo -en 'travis_fold:start:Mtac2.build\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/Mtac2
    ./configure.sh
    make
    make test
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:Mtac2.build\\r'

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/2fc197f36f7c587c0f59
        - https://mattermost.mpi-sws.org/hooks/tyg3f3w7gpdaprgo1krzc94j7o
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
