[package]
name = "to_flamegraph"
version = "0.1.0"
authors = ["Jan-Oliver Kaiser <janno@mpi-sws.org>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
sequence_trie = "0.3.5"
lalrpop-util = "0.15.2"
regex = "0.2.1"
lazy_static = "1.0.0"