# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, master-*, staging, trying ]
  pull_request:
    branches: [ master, master-*, staging, trying ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: coqorg/coq:dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install Unicoq master
        run: |
          export OPAMJOBS="2"
          set -ex
          opam config list
          opam repo list
          opam list
          opam update default
          coqc --version
          opam pin add https://github.com/unicoq/unicoq.git#master -k git -y
          opam pin
          opam list

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Build Mtac2
        run: |
          docker exec COQ /bin/bash --login -c "
          export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
          set -ex
          cd "$GITHUB_WORKSPACE"
          sudo chown -R coq:coq .
          ./configure.sh
          make
          make test
